SnackHubUI/Pages/CurrencyAdmin.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SnackHubLibrary.Logic;
using SnackHubLibrary.Models;
using System.Collections.Generic;
using System.Linq;

namespace SnackHubUI.Pages
{
    // Removed for due to demo purposes 
    //[Authorize(Roles ="Admin")]
    public class CurrencyAdminModel : PageModel
    {
        private readonly ISnackHubLogic _snackHub;

        public List<CurrencyModel> Change { get; set; }

        public CurrencyAdminModel(ISnackHubLogic snackHub)
        {
            _snackHub = snackHub;
        }

        [BindProperty]
        public CurrencyModel ChangeToAdd { get; set; } = new CurrencyModel();

        /// <summary>
        /// Admin is able to add change to the inventory
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPost()
        {
            _snackHub.AddMoneyToInventory(new List<CurrencyModel> { ChangeToAdd});
            return RedirectToPage();
        }

        /// <summary>
        /// Get current inventory of the money 
        /// </summary>
        public void OnGet()
        {
            Change = _snackHub.GetChangeInventory().OrderBy(y => y.Name).ToList();
        }
    }
}

SnackHubUI/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SnackHubRazorUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SnackHubUI/Pages/GenerateAdmin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace SnackHubRazorUI
{
    public class GenerateAdminModel : PageModel
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IConfiguration _config;
        private const string adminRole = "Admin";

        public bool RoleCreated { get; set; }
        public string AdminUserId { get; set; }

        public GenerateAdminModel(RoleManager<IdentityRole> roleManager,
                                  UserManager<IdentityUser> userManager,
                                  IConfiguration config)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _config = config;
        }

        /// <summary>
        /// Create the admin role type if it doesnt exist using an email to provide the value 
        /// </summary>
        /// <returns></returns>
        public async Task OnGet()
        {
            //check if admin role exists
            var roleExists = await _roleManager.RoleExistsAsync(adminRole);

            // Create it if it doesnt
            if (roleExists == false)
            {
                await _roleManager.CreateAsync(new IdentityRole(adminRole));
                RoleCreated = true;
            }

            // Get users email id from app config file and then add them to the admin role 
            string userEmail = _config.GetValue<string>("AdminUser");

            var user = await _userManager.FindByEmailAsync(userEmail);

            if (user != null)
            {
                await _userManager.AddToRoleAsync(user, adminRole);
                AdminUserId = user.Id;
            }
        }
    }
}

SnackHubUI/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SnackHubRazorUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

SnackHubUI/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace SnackHubRazorUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SnackHubUI/Pages/SnackHub.cshtml.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SnackHubLibrary.Logic;
using SnackHubLibrary.Models;

namespace SnackHubRazorUI
{
    [Authorize]
    public class SnackHubModel : PageModel
    {
        private readonly ISnackHubLogic _snackHub;

        public decimal SnackPrice { get; set; }
        public decimal AmountInserted { get; set; }
        public List<SnackModel> SnackOptions { get; set; }

        [BindProperty]
        public decimal Deposit { get; set; }

        [BindProperty]
        public SnackModel SelectedSnack { get; set; }

        public string UserId { get; set; }

        [BindProperty(SupportsGet = true)]
        public string OutputText { get; set; }

        [BindProperty(SupportsGet = true)]
        public string ErrorMessage { get; set; }

        public SnackHubModel(ISnackHubLogic snackHub)
        {
            _snackHub = snackHub;
        }

        /// <summary>
        /// On startup get all the data we need and authorize a valid user 
        /// </summary>
        public void OnGet()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            SnackPrice = _snackHub.GetSnackPrice();
            AmountInserted = _snackHub.GetTotalMoneyInserted(UserId);
            SnackOptions = _snackHub.ListTypesOfSnack();
        }

        /// <summary>
        /// Used for depositing change and post the request
        /// </summary>
        /// <returns></returns>

        public IActionResult OnPost()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (Deposit > 0)
            {
                _snackHub.MoneyInserted(UserId, Deposit);
            }

            return RedirectToPage();
        }

        /// <summary>
        /// Method requests a snack once change has been inserted into the machine
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPostSnack()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var results = _snackHub.RequestSnack(SelectedSnack, UserId);
            OutputText = "";

            // Handle the response
            if (results.errorMessage.Length > 0)
            {
                ErrorMessage = results.errorMessage;
            }
            else
            {
                OutputText = $"Here is your tasty treat {results.snack.SnackName}. ENJOY!";

                if (results.change.Count > 0)
                {
                    OutputText += "<br><br>Here is your change back. Have a nice day!:<br>";
                    results.change.ForEach(x => OutputText += $"{x.Name}<br>");
                }
                else
                {
                    OutputText += "<br><br>You used exact change. Nothing to refund. Thank you!";
                }
            }

            return RedirectToPage(new { ErrorMessage, OutputText });
        }

        /// <summary>
        /// Issue a refund to the user if transaction is cancelled 
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPostCancel()
        {
            UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            AmountInserted = _snackHub.GetTotalMoneyInserted(UserId);
            _snackHub.IssueEntireRefund(UserId);

            OutputText = $"You have been refunded {String.Format("{0:C}", AmountInserted)}. Please take your change";

            return RedirectToPage(new { OutputText });
        }
    }
}

SnackHubUI/Pages/CurrencyAdmin.cshtml
@page
@model SnackHubUI.Pages.CurrencyAdminModel
@{
    ViewData["Title"] = "CurrencyAdmin";
}

<h1>CurrencyAdmin</h1>

<div class="row">
    <div class="col-6">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var row in Model.Change)
                {
                    <tr>
                        <td>@row.Name</td>
                        <td>@row.Amount</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-6">

        <form method="post">
            <input type="hidden" asp-for="ChangeToAdd.Name" value="Nickle" />
            <input type="hidden" asp-for="ChangeToAdd.Amount" value="0.05" />
            <button type="submit" class="btn btn-primary">Nickle</button>
        </form>
        <br />

        <form method="post">
            <input type="hidden" asp-for="ChangeToAdd.Name" value="Dime" />
            <input type="hidden" asp-for="ChangeToAdd.Amount" value="0.10" />
            <button type="submit" class="btn btn-primary">Dime</button>
        </form>
        <br />

        <form method="post">
            <input type="hidden" asp-for="ChangeToAdd.Name" value="Quarter" />
            <input type="hidden" asp-for="ChangeToAdd.Amount" value="0.25" />
            <button type="submit" class="btn btn-primary">Quarter</button>
        </form>

    </div>
</div>

SnackHubUI/Pages/GenerateAdmin.cshtml
@page
@model SnackHubRazorUI.GenerateAdminModel
@{
    ViewData["Title"] = "GenerateAdmin";
}

<h1>Generate Admin</h1>

<h2>Role Created For User: @Model.RoleCreated</h2>
<h2>Admin UserId: @Model.AdminUserId</h2>

SnackHubUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SnackHubUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SnackHubUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SnackHubUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/SnackHub">Snack Hub</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/CurrencyAdmin">CurrencyAdmin</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SnackHubUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

SnackHubUI/Pages/SnackHub.cshtml
@page
@model SnackHubRazorUI.SnackHubModel
@{
    ViewData["Title"] = "Snack Hub";
}
<!-- https://getbootstrap.com -->

<h1>Snack Hub</h1>
<h5>Snack Price: @String.Format("{0:C}", Model.SnackPrice)</h5>
<h5>Amount Inserted: @String.Format("{0:C}", Model.AmountInserted)</h5>

@if (String.IsNullOrWhiteSpace(Model.ErrorMessage) == false)
{
    <p class="text-danger">
        @Model.ErrorMessage
    </p>
}

<div class="row">
    <div class="col-sm-8">
        @foreach (var snack in Model.SnackOptions)
        {
            <div class="row">
                <div class="col-sm-8 snack-tab bg-secondary text-white">
                    @snack.SnackName
                </div>
                <div class="col-sm-4">
                    <form method="post" asp-page-handler="Snack">
                        <input type="hidden" asp-for="UserId" />
                        <input type="hidden" asp-for="SelectedSnack.SnackName" value="@snack.SnackName" />
                        <input type="hidden" asp-for="SelectedSnack.OccupiedSlot" value="@snack.OccupiedSlot" />
                        <button type="submit" class="btn btn-primary btn-snack">Buy</button>
                    </form>
                </div>
            </div>
        }
    </div>
    <div class="col-sm-4">
        @Html.Raw(Model.OutputText)
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <h3>Deposit Change</h3>
        <div class="btn-group" role="group">
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.05" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.05)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.10" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.10)</button>
            </form>
            <form method="post">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="Deposit" value="0.25" />
                <button type="submit" class="btn btn-primary">@String.Format("{0:C}", 0.25)</button>
            </form>
        </div>
    </div>
    <div class="col-sm-4">
        <h3>Cancel Sale</h3>
        <form method="post" asp-page-handler="Cancel">
            <input type="hidden" asp-for="UserId" />
            <button type="submit" class="btn btn-danger">Refund Money</button>
        </form>
    </div>
</div>